# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['sailwind_editor.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('core.py', '.'),
        ('ui.py', '.'),
    ],
    hiddenimports=[
        'flet',
        'flet.core',
        'flet.controls',
        'flet.controls.text',
        'flet.controls.textfield',
        'flet.controls.button',
        'flet.controls.filepicker',
        'flet.controls.progressbar',
        'flet.controls.text',
        'flet.controls.button',
        'flet.controls.checkbox',
        'flet.controls.dropdown',
        'flet.controls.row',
        'flet.controls.column',
        'flet.controls.container',
        'flet.controls.appbar',
        'flet.controls.icon',
        'flet.controls.divider',
        'flet.controls.tabs',
        'flet.controls.tab',
        'flet.controls.card',
        'flet.controls.listview',
        'flet.controls.gridview',
        'flet.controls.alertdialog',
        'flet.controls.textfield',
        'flet.controls.filledbutton',
        'flet.controls.outlinedbutton',
        'flet.controls.iconbutton',
        'flet.controls.textbutton',
        'flet.controls.elevatedbutton',
        'flet.controls.floatingactionbutton',
        'flet.controls.tooltip',
        'flet.controls.gesturedetector',
        'flet.controls.stack',
        'flet.controls.shader_mask',
        'flet.controls.opacity',
        'flet.controls.rotation',
        'flet.controls.scale',
        'flet.controls.transform',
        'flet.controls.animate',
        'flet.controls.animation',
        'flet.core.control',
        'flet.core.control_event',
        'flet.core.event',
        'flet.core.animation',
        'flet.core.animation_curve',
        'flet.core.border',
        'flet.core.border_radius',
        'flet.core.padding',
        'flet.core.margin',
        'flet.core.alignment',
        'flet.core.colors',
        'flet.core.fonts',
        'flet.core.icons',
        'flet.core.theme',
        'flet.core.theme_mode',
        'flet.core.control_event',
        'flet.core.file_picker_result',
        'flet.core.event_handler',
        'flet.core.protocol',
        'flet.core.protocol_handler',
        'flet_runtime',
        'flet_runtime.python',
        'nrbf',
        'nrbf.nrbf',
        'nrbf.parser',
        'nrbf.serializer',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='sailwind_editor',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)